i removed .env file from .gitignore and push it to gitlab then vercel run build again but i dont know if this a best practice or not but i got different error
 Generating static pages (0/13) ...
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/investments/add". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at s (/vercel/path0/.next/server/chunks/413.js:3:24235)
    at d (/vercel/path0/.next/server/chunks/413.js:25:75477)
    at n (/vercel/path0/.next/server/chunks/809.js:1:6802)
    at nL (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46773)
    at nF (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48548)
    at nF (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64360)
    at nq (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67434)
    at nH (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65009)
    at nV (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:70865)
    at nF (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:60898)
Error occurred prerendering page "/investments/add". Read more: https://nextjs.org/docs/messages/prerender-error
Export encountered an error on /(app)/investments/add/page: /investments/add, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null
Error: Command "npm run build" exited with 1